config/routes.rb
Rails.application.routes.draw do
  # root "newspapers#index" 
  root "articles#show"
  get 'crawl', action: :crawl, controller: 'newspapers'
  resources :newspapers do

    resources :articles
  end
  # get 'newspapers/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :newspaper

  validates :headline, presence: true
  validates :url, presence: true, uniqueness: true 
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
  has_many :articles
 
  validates :newspaperName, presence: true, uniqueness: true
  validates :newspaperUrl, presence: true, uniqueness: true
  validates :newspaperCssSelector, presence: true
  validates :newspaperArticleUrlAppend, presence: true
 
  p 'Time in MODEL: '
  p Time.now
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    p "Show"
    p Article.all
    
    # @newspaper = Newspaper.find(params[:newspaper_id])
    # @article = @newspaper.articles.create(article_params)
    
  end

  def create
    @newspaper = Newspaper.find(params[:newspaper_id])
    @article = @newspaper.articles.create(article_params)
    redirect_to newspaper_path(@newspaper)
  end

  private
    def article_params
      params.require(:article).permit(:url, :headline)
    end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  def index
    @newspapers = Newspaper.all
  end

  def show
    @newspaper = Newspaper.find(params[:id])
  end

  def new
    @newspaper = Newspaper.new
  end

  def create
    @newspaper = Newspaper.new(newspaper_params)

    if @newspaper.save
      redirect_to @newspaper
    else
      render :new
    end
  end

  def edit
    @newspaper = Newspaper.find(params[:id])
  end

  def update
    @newspaper = Newspaper.find(params[:id])

    if @newspaper.update(newspaper_params)
      redirect_to @newspaper
    else
      render :edit
    end
  end

  def destroy
    @newspaper = Newspaper.find(params[:id])
    @newspaper.destroy

    redirect_to root_path
  end

  def crawl  
 
      Newspaper.all.each do |newspaper|
        thisUrl = newspaper.newspaperUrl 
        html = URI.open("#{thisUrl}").read 
        header = Nokogiri::HTML(html)  
        headers = header.css(newspaper.newspaperCssSelector)
        urlAppend =  headers[0].attribute('href').value
        retrievedArticleHeadline = headers[0].content; 
        retrievedArticleUrl = thisUrl + urlAppend 
      @article = Article.new(headline: retrievedArticleHeadline, url: retrievedArticleUrl, newspaper_id: newspaper.id)
      # p @article.valid?
      if(@article.save)then p "Article saved!" else p "Article not saved. It's already in the db!" end 
       
    end





  end
  private

  def newspaper_params
    params.require(:newspaper).permit(:newspaperName, :newspaperUrl, :newspaperCssSelector, :newspaperArticleUrlAppend)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/articles/show.html.erb
<h1>Ultimas noticias</h1> 
<div class="article-wrapper">
<% Article.all.each do |article| %> 
<div class="article-item">
    <a href="<%= article.url %>" target="_blank">
      <h2 class="article-headline">
        <%= article.headline %>
      </h2>
    </a> 
    <div>
      Fuente:
      <% source = article.newspaper_id %>
      
      <%= Newspaper.find(source).newspaperName %> 
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiptopnews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newspapers/_form.html.erb
<%= form_with model: newspaper do |form| %>
  <div>
    <%= form.label :newspaperName %><br>
    <%= form.text_field :newspaperName %>
    <% newspaper.errors.full_messages_for(:newspaperName).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :newspaperUrl %><br>
    <%= form.text_field :newspaperUrl %>
    <% newspaper.errors.full_messages_for(:newspaperUrl).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :newspaperCssSelector %><br>
    <%= form.text_field :newspaperCssSelector %>
    <% newspaper.errors.full_messages_for(:newspaperCssSelector).each do |message| %>
    <div><%= message %>
  </div>
    <% end %>
    
    <div>
    <%= form.label :newspaperArticleUrlAppend %><br>
    <%= form.text_field :newspaperArticleUrlAppend %>
    <% newspaper.errors.full_messages_for(:newspaperArticleUrlAppend).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>
 
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newspapers/crawl.html.erb
<h1>CRAWL</h1>
<%= Time.now %>
<% p 'Time in crawl: ' %>
<% p Time.now %>

app/views/newspapers/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", newspaper: @newspaper %>

app/views/newspapers/index.html.erb
<h1>Newspapers#index</h1>
<p>Find me in app/views/newspapers/index.html.erb</p>


<h1>Articles</h1>

<ul>
  <% @newspapers.each do |newspaper| %>
    <li>
      <%= link_to newspaper.newspaperName, newspaper %>
    </li>
  <% end %>
</ul>

<%= link_to "Add new newspaper", new_newspaper_path %>

app/views/newspapers/new.html.erb
<h1>New newspaper</h1>
<%= render "form", newspaper: @newspaper %>

app/views/newspapers/show.html.erb
<br><br><br><br>
<%= @newspaper.id %><br>
<%= @newspaper.newspaperName %><br>
<%= @newspaper.newspaperUrl %><br>
<%= @newspaper.newspaperCssSelector %><br>
<%= @newspaper.newspaperArticleUrlAppend %><br>

<ul>
  <li><%= link_to "Edit", edit_newspaper_path(@newspaper) %></li>
    <li><%= link_to "Destroy", newspaper_path(@newspaper),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>


<h2>Articles</h2>
<% @newspaper.articles.each do |article| %>
  <p>
    <strong>Url: </strong>
    <%= article.url %>
  </p>

  <p>
    <strong>Headline:</strong>
    <%= article.headline %>
  </p>
<% end %>




<h2>Add a comment:</h2>
<%= form_with model: [ @newspaper, @newspaper.articles.build ] do |form| %>
  <p>
    <%= form.label :headline %><br>
    <%= form.text_field :headline %>
  </p>
  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>